{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ptrun.serviceAccountName" . }}
  labels:
    {{- include "ptrun.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotatios }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.client.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ptrun.serviceAccountName" . }}
  labels:
    {{- include "ptrun.labels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotatios }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

