apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptrun.fullname" . }}
  labels:
    {{- include "ptrun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptrun.selectorLabels" . | nindent 4 }}
    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptrun.fullname" . }}
  labels:
    {{- include "ptrun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptrun.selectorLabels" . | nindent 4 }}
