FROM golang:1.16-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN protoc --proto_path=./messages --go_out=./ messages/*.proto
RUN go build -o ptrun-server ./server/cmd/ptrun-server/main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/ptrun-server ./ptrun-server

EXPOSE 8080
CMD [ "./ptrun-server" ]
