FROM golang:1.16-alpine AS builder

COPY . /app

WORKDIR /app/server

RUN apk add --no-cache protoc && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    protoc --proto_path=../messages --go_out=../ ../messages/*.proto && \
    go mod download && \
    go build -o ../ptrun-server ./cmd/ptrun-server/main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/ptrun-server ./ptrun-server

EXPOSE 8080
CMD [ "./ptrun-server" ]
